### ISSUE TITLE
Fix resolution in bottom level images

### ISSUE THREAD

**Issue by gdunstone** [borevitzlab/exif2timestream#28]
The height shouldnt be in the lowest level files
see: 
``` 
fnqr-daintree-overstory-nadir-C01~1920x1440-orig_2014_04_05_06_00_00_00.jpg
```

should be:
```
fnqr-daintree-overstory-nadir-C01~1920-orig_2014_04_05_06_00_00_00.jpg
```

I have mangled the data that we have in the "supersites_read_only" folder, so that it will work, but this is still an issue until it is fixed in this library

**Comment by gdunstone** [comment]
also the names under original and outputs should not have underscores in them:
```
fnqr-daintree-understory_oblique-01~fullres-orig
```
should be
```
fnqr-daintree-understory-oblique-01~fullres-orig
```

**Comment by jbraiuka** [comment]
Should be done under latest push. Thanks.
